# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-08 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('CPF', models.CharField(max_length=11)),
                ('Data_de_Nascimento', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('Nacionalidade', models.CharField(max_length=15)),
                ('Titulos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateTimeField()),
                ('Resultado', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Razão_Social', models.CharField(max_length=50)),
                ('Mascote', models.ImageField(max_length=20, upload_to='')),
                ('CNPJ', models.CharField(max_length=14)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Time_Jogador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inicio_do_Contrato', models.DateField()),
                ('Termino_do_Contrato', models.DateField()),
                ('Jogador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Jogador')),
                ('Time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Time')),
            ],
        ),
    ]
